#!/bin/bash

# Auto Betty Checker
# Author Jashon Osala
# 2022
# Betty linter

# VARS
DATA="__dump_file"
ERR=("ERROR" "WARNING")
CR="\n"
UNDONE="Stopping all other checks"
NULL_OUT="/dev/null 2>&1"

# Files
README_FILE="README.md"
REPO_NAME="alx-higher_level_programming"

# Errors
README_ERROR_0="Readme file not present"
README_ERROR_1="Readme file is empty"
REPO_ERROR_0="The repository does not exist"
BETTY_ERROR="Betty check failed with the following errors"


# Color schemes
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'

HOME_DIR="."
TOOL_DIR="suites"

run_checker () {
	for ((i=$(($1)); i <= $(($2)); i=$(($i + 1)))); do
		${HOME_DIR}/${TOOL_DIR}/mark $i $3
	done
}

wild_file () {
	for i in $1; do
		if [ -f $i ]; then
			return 1
		fi
	done
	return 0
}

echo -e
echo -e "${GREEN}===================Betty Checks===================${NC}"
echo -e



for d in */; do
	if [ $((wild_file "${d}*.c")) -ge 1 ]; then
		./suites/betty "${d}*.c" >> $DATA
	fi
	if [ $((wild_file "${d}*.h")) -ge 1 ]; then
		./suites/betty "${d}*.c" >> $DATA
	fi
done

if [ ! -f "$DATA" ]; then
	echo -e
	echo -e "${GREEN}Test 0:${NC} Betty linter found no *.c or *.h files to to check${CR}${UNDONE}" 1>&2
	echo -e
	exit 0
fi

for i in $ERR; do
	if [ "$(grep -c $i $DATA)" -ge 1 ]; then
		echo -e
		echo -e "${BETTY_ERROR}${CR}${RED}`cat $DATA`${NC}" 1>&2
		exit 64
	fi
done

# cleanup

rm $DATA
echo -e
echo -e "ALL ${GREEN}checks${NC} compleated successfully"
echo -e
