#!/bin/bash

BETTY_PATH="suites"
BETTY_STYLE="betty_style"
BETTY_DOC="betty_doc"

if [ "$#" = "0" ]; then
    echo "No arguments passed."
    exit 1
fi

for argument in "$@" ; do
    echo -e "\n========== $argument =========="
    ./${BETTY_PATH}/${BETTY_STYLE} "$argument"
    ./${BETTY_PATH}/${BETTY_DOC} "$argument"
done
