#!/bin/bash

# Simple shell checker 
# Author Jashon Osala
# 2022
# Task 0

# VARS
DATA="__dump_file"
ERR="ERROR"
CR="\n"
UNDONE="Stopping all other checks"

# Files
README_FILE="README.md"
AUTHORS_FILE="AUTHORS"
REPO_NAME="simple_shell"

# Errors
README_ERROR_0="Readme file not present"
README_ERROR_1="Readme file is empty"
AUTHORS_ERROR_0="Authors file not present"
AUTHORS_ERROR_1="Authors file is empty"
REPO_ERROR_0="The repository does not exist"
BETTY_ERROR="Betty check failed with the following errors"


# Color schemes
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'

HOME_DIR="."
TOOL_DIR="suites"

run_checker () {
	for ((i=$(($1)); i <= $(($2)); i=$(($i + 1)))); do
		${HOME_DIR}/${TOOL_DIR}/mark $i $3
	done
}

# Test 0
echo -e
echo -e "===================Test 0==================="
echo -e
echo -e

# Repository is exist
if [ ! -d "../$REPO_NAME" ]; then
	run_checker 0 6 0
	echo -e "Test 0: ${REPO_ERROR_0}${CR}${UNDONE}" 1>&2
	echo -e
	exit 64
fi

# Readme file present
if [ ! -f "$README_FILE" ]; then
	run_checker 0 0 1
        run_checker 1 6 0
	echo -e
	echo -e "Test 0: ${README_ERROR_0}${CR}${UNDONE}" 1>&2
	echo -e
	exit 64
fi

# Readme file is empty
if [ ! -s "$README_FILE" ]; then
        run_checker 0 1 1
        run_checker 2 6 0
	echo -e
	echo -e "Test 0: ${README_ERROR_1}${CR}${UNDONE}" 1>&2
	echo -e
	exit 64
fi

# Authors file present
if [ ! -f "$AUTHORS_FILE" ]; then
        run_checker 0 2 1
        run_checker 3 6 0
	echo -e
	echo -e "Test 0: ${AUTHORS_ERROR_0}${CR}${UNDONE}" 1>&2
	echo -e
	exit 64
fi

# Authors file empty
if [ ! -s "$AUTHORS_FILE" ]; then
        run_checker 0 3 1
        run_checker 4 6 0
       	echo -e
	echo -e "Test 0: ${AUTHORS_ERROR_1}${CR}${UNDONE}" 1>&2
	echo -e
	exit 64
fi

# betty

./suites/betty *.c *.h > $DATA

if [ ! -f "$DATA" ]; then
        run_checker 0 4 1
        run_checker 5 6 0
	echo -e
	echo -e "Test 0: Betty checker failed to launch${CR}${UNDONE}" 1>&2
	echo -e
	exit 64
fi


if [ "$(grep -c $ERR $DATA)" -ge 1 ]; then
	run_checker 0 5 1
	run_checker 6 6 0
	echo -e
	echo -e "${BETTY_ERROR}${CR}${RED}`cat $DATA`${NC}" 1>&2
	exit 64
fi

# cleanup
run_checker 0 6 1

rm $DATA
echo -e
echo -e "ALL ${GREEN}checks${NC} compleated successfully"
echo -e
