#!/bin/bash

# Simple shell checker 
# Author Jashon Osala
# 2022

TEST_DOC="local_check"

if ! -f $TEST_DOC; then
	echo -e "No checks to run"
	exit 1 "Missing check file"
fi

call_check () {
	case "$1" in
		"CHECK_00") echo -e "Task 0: Checks"
			curl 
